CC := gcc
CFLAGS = -O0 -w 

#CFLAGS := -O0 -pthread -D_POSIX_C_SOURCE=200112

#CC := clang 
#CFLAGS := -O -pthread -D_POSIX_C_SOURCE=200112 -static -integrated-as -msoft-float



#CFLAGS := -g3 -pthread -D_POSIX_C_SOURCE=200112

#CFLAGS := $(CFLAGS) -Wall -W -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wdisabled-optimization
#CFLAGS := $(CFLAGS) -Wpadded -Winline -Wpointer-arith -Wsign-compare -Wendif-labels

#LDFLAGS := -lm
LDFLAGS = -lmpc -lm -pthread
#LDFLAGS := -lm -static

#BASEDIR := $(HOME)/splash2/codes

MACROS := ../null_macros/c.m4.null
M4 := m4 -s -Ulen -Uindex

x = *

$(TARGET): $(OBJS)
	$(CC) $(OBJS) $(CFLAGS) -o $(TARGET) $(LDFLAGS)

clean:
	rm -rf *.c *.h *.o $(TARGET)

.SUFFIXES:
.SUFFIXES:	.o .c .C .h .H

.H.h:
	$(M4) $(MACROS) $*.H > $*.h

.C.c:
	$(M4) $(MACROS) $*.C > $*.c

.c.o:
	$(CC) -c $(CFLAGS) $*.c

.C.o:
	$(M4) $(MACROS) $*.C > $*.c
	$(CC) -c $(CFLAGS) $*.c
